### ISSUE TITLE
Add SOCKS5 support to libight

### ISSUE THREAD

**Issue by hellais** [TheTorProject/libight#47]
To support sending TCP connections over Tor we need to support the SOCKS5 (or SOCKS4a) protocol in libight.

This functionality should be exposed in two manners:

1) Directly via the `Connection` object

2) By passing a special `Options` keys to `ight.net.http`

**Comment by bassosimone** [comment]
Implemented by #71. I decided not to use Trunnel because we already had enough abstractions in libight to easily implement SOCKSv5 in a C++-ish way.
